### Anything added to crawler_user_config.yml will overwrite these settings

# Max concurrent threadpool workers - setting this too high may cause connections to be dropped
#threads: 1000
threads: 500

# Max tasks in queue - higher will minimize database IO at cost of increased memory usage
max_queue: 20000

# Minimum time between node visitations (minutes)
crawl_interval: 15

# Proportion of connections which are followed up with a getaddr call. (0.0-1.0)
# After initial seeding it isn't necessary for this to be very high to discover all new nodes
# When --seed parameter is passed this is ignored
getaddr_prop: 0.15
#getaddr_prop: 1

# How much the block height has to differ from the median to be marked inactive
# Dash and Litecoin have faster block times so this is set slightly higher
inactive_threshold:
  default: 12
  dash: 48
  litecoin: 48
  litecoin-testnet: 48

# Attempt to establish connection with IPv6 nodes
ipv6: True

# Attempt to establish connection with .onion nodes
onion: True

# Tor proxy is required to connect to .onion address
tor_proxy:
  - 127.0.0.*:9050
  - 127.0.0.*:9052
  - 127.0.0.*:9053
  - 127.0.0.*:9054
  - 127.0.0.*:9055
  - 127.0.0.*:9056
  - 127.0.0.*:9057
  - 127.0.0.*:9058
  - 127.0.0.*:9059
  - 127.0.0.*:9060
  - 127.0.0.*:9061
  - 127.0.0.*:9062
  - 127.0.0.*:9063
  - 127.0.0.*:9064
  - 127.0.0.*:9065
  - 127.0.0.*:9066
  - 127.0.0.*:9067

# order with which to process the networks - bch should be processed first, as all bch nodes need to be mapped so
# they are not pinged while crawling another network. Connections to BCH nodes with the wrong network-magic will
# trigger a 24 hour IP ban.
crawl_order:
  - bitcoin-cash
  - bch-testnet3
  - bch-testnet4
  - bch-scalenet
  - dash
  - zcash
  - dogecoin
  - litecoin
  - litecoin-testnet
  - bitcoin
  - bitcoin-testnet
  - bitcoin-signet

# Locks database table and updates Last_Checked BEFORE crawling nodes
# Performance overhead, but necessary if multiple processes are crawling concurrently using the same database
database_concurrency: False

# Socket timeout (seconds)
socket_timeout: 20
tor_socket_timeout: 120

# Retries
retries: 1

# Retry only nodes seen in past X hours
retry_threshold: 12

# Used during connection handshake
#user_agent: /Satoshi:22.0.0/
user_agent: /MagicBean:5.0.0/
source_address: 0.0.0.*

# How many days to continue checking a node that has not yet been seen
min_pruning_age: 2

# How many days to continue checking a node that has previously been seen
max_pruning_age: 0

# If a seen node has been pruned from the database due to max_pruning_age, remove its visitation history as well
prune_visitations: False

# Active nodes are defined as nodes within +/- [inactive_threshold] of the median block height.
# If false inactive nodes will not be reported in the dumped files
export_inactive_nodes: True

# Excluded user agents - regex (see https://docs.python.org/3/library/re.html)
excluded_user_agents:
  - /monoeci*
  - /binarium*
  - /qyno*
  - /monaco*
  - /digitalcoin*
  - /flashcoin*
  - /watertechnology*
  - /worldcoin*
  - /feathercoin*
  - /cryptocoin*
  - /sollida*
  - /lkscoin*
  - /futurebit*
  - /desire*

# Lookup whether a node is a Dash masternode or not
get_dash_masternodes: True

# dash-masternodes-api-endpoint - used as a fallback if local node is not running
# GET/POST request should return a json array of all active dash masternodes
# e.g. https://running-opennodes-webserver.com/api/get_dash_masternodes
#curl --location --request POST 'https://eth.getblock.io/mainnet/' --header 'x-api-key: 30c5d860-5ab2-4233-b4aa-89e805b44fa2' --header 'Content-Type: application/json' --data-raw '{"id": "blockNumber", "jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", false]}'
dash_masternodes_api: ''

# dash-cli executable directory
dash_cli_path: /mnt/HC_Volume_2167606/dashcore-0.13.2/bin/

# historical data reporting interval (hours)
historic_interval: 4

# Protocol info for crawled networks
networks:
  bitcoin:
    services: 0
    magic_number: f9beb4d9
    port: 8333
    protocol_version: 70016
    min_protocol_version: 70001
    dns_seeds:
      - seed.btc.petertodd.org
      - seed.bitcoin.sprovoost.nl
      - dnsseed.emzy.de
      - dnsseed.bitcoin.dashjr.org
      - dnsseed.bluematt.me
      - seed.bitcoin.jonasschnelli.ch
      - seed.bitcoin.sipa.be
      - seed.bitcoinstats.com
      - seed.btc.petertodd.org
      - seed.bitnodes.io
      - seed.bitcoinabc.org
      - seed.bitcoinunlimited.info
      - btccash-seeder.bitcoinunlimited.info
      - seed.deadalnix.me
    address_seeds:
      - wioaxcgen3qvoqbf.onion
      - hpquscklwzoiw7qv.onion
      - 2zfhqfr4buzvrl5y.onion
      - wgjotdhmpcj2kyq2.onion
      - l4xfmcziytzeehcz.onion
      - 36xxwca2o6gz2h2b.onion
      - 7ejgnxi5z4w6tcgc.onion
      - rlxhnlonhjiyzhjb.onion
      - 62au2pzqah7cnrrw.onion
      - 5difox54jm5hplrw.onion
      - jwplkr5q3fivotmz.onion
      - ndndword5lpb7eex.onion
  dash:
    services: 0
    magic_number: bf0c6bbd
    port: 9999
    protocol_version: 70215
    min_protocol_version: 70001
    dns_seeds:
      - dnsseed.darkcoin.io
      - dnsseed.dashdot.io
      - dnsseed.masternode.io
      - dnsseed.dashpay.io
      - dnsseed.dash.org
    address_seeds:
      - 128.199.62.*
      - 31.220.7.*
      - 89.38.144.*
      - 188.166.9.*
      - 45.32.114.*
      - 37.59.247.*
      - 149.56.66.*
      - 159.65.84.*
      - 185.158.152.*
      - 45.32.20.*
      - 52.79.197.*
      - 51.15.88.*
  bitcoin-testnet:
    services: 0
    magic_number: 0b110907
    port: 18333
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - testnet-seed.bitcoin.jonasschnelli.ch
      - seed.tbtc.petertodd.org
      - seed.testnet.bitcoin.sprovoost.nl
      - testnet-seed.bluematt.me
    address_seeds:
      -
  bitcoin-signet:
    services: 0
    magic_number: 0A03CF40
    port: 38333
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - 178.128.221.*
      - 2a01:7c8:d005:390:*
      - v7ajjeirttkbnt32wpy3c6w3emwnfr3fkla7hpxcfokr3ysd3kqtzmqd.onion:38333
    address_seeds:
      -
  litecoin:
    services: 0
    magic_number: fbc0b6db
    port: 9333
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - dnsseed.litecointools.com
      - dnsseed.litecoinpool.org
      - dnsseed.ltc.xurious.com
      - dnsseed.koin-project.com
      - seed-a.litecoin.loshan.co.uk
      - dnsseed.thrasher.io
    address_seeds:
      - phrj27hskw3gq4b5.onion
      - 2oqq4rydtti3xq4n.onion
      - 4xjze2q2ztn6l4ce.onion
      - 5zkvemmfa7ylr2qs.onion
      - mqgmba4o453jwdjd.onion
      - czahaqs6fhwr3jmw.onion
  litecoin-testnet:
    services: 0
    magic_number: fdd2c8f1
    port: 19335
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - dnsseed-testnet.thrasher.io
      - testnet-seed.litecointools.com
      - seed-b.litecoin.loshan.co.uk
      - 2a01:4f8:231:645:*
      - 2600:3c02::f03c:*:*:*:*:*:*
      - 2001:bc8:1830:1312:*
      - 2804:14c:bbad:403b:*
    address_seeds:
      - 3.216.93.*:19335
      - 5.196.127.*:19335
      - 45.33.107.*:19335
      - 45.33.107.*:19335
      - 47.74.241.*:19335
      - 47.75.43.*:19335
      - 47.104.65.*:19335
      - 51.158.170.*:19335
      - 54.37.77.*:19335
      - 54.187.94.*:19335
      - 54.201.44.*:19335
  bitcoin-cash:
    services: 0
    magic_number: e3e1f3e8
    port: 8333
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - seed.flowee.cash
      - seed-bch.bitcoinforks.org
      - btccash-seeder.bitcoinunlimited.info
      - seed.bchd.cash
      - seed.bch.loping.net
      - dnsseed.electroncash.de
      - bchseed.c3-soft.com
      - seed.bitcoinabc.org
      - seed-abc.bitcoinforks.org
      - seed.bitcoinunlimited.info
      - seed.bitprim.org
      - seed.deadalnix.me
      - seeder.criptolayer.net
    address_seeds:
      - li2mrdnveswxiwpe.onion
      - bchponzidlqjpsqp.onion
      - kister7332my5jka.onion
      - nld6rvbglzbbf7av.onion
      - wxjlz4avds42d42o.onion
      - wxh5kn2zjkcptpvo.onion
      - zndv4khma6ikx7o3.onion
      - kisternetg2pq7wx.onion
  bch-testnet3:
    services: 0
    magic_number: f4e5f3f4
    port: 18333
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - testnet-seed-bch.bitcoinforks.org
      - testnet-seed.bchd.cash
      - seed.tbch.loping.net
    address_seeds:
      -
  bch-testnet4:
    services: 0
    magic_number: e2b7daaf
    port: 28333
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - testnet4-seed-bch.bitcoinforks.org
      - testnet4-seed-bch.toom.im
      - seed.tbch4.loping.net
      - testnet4-seed.flowee.cash
    address_seeds:
      -
  bch-scalenet:
    services: 0
    magic_number: c3afe1a2
    port: 38333
    protocol_version: 70015
    min_protocol_version: 70001
    dns_seeds:
      - scalenet-seed-bch.bitcoinforks.org
      - scalenet-seed-bch.toom.im
      - seed.sbch.loping.net
    address_seeds:
      -
  zcash:
    services: 0
    magic_number: 24e92764
    port: 8233
    protocol_version: 170100
    min_protocol_version: 170002
    dns_seeds:
      - dnsseed.z.cash
      - dnsseed.str4d.xyz
      - mainnet.seeder.zfnd.org
      - mainnet.is.yolo.money
    address_seeds:
      - zcmaintvsivr7pcn.onion
      - zcashiqykswlzpsu.onion
      - zcashqhrmju6zfhn.onion
      - zcashgmvxwrmjsut.onion
      - zcashz3uma65ix7b.onion
      - zcashiyf4kxluf3x.onion
      - zcashwfe4x3jkz2b.onion
      - zcashvkeki52iqpc.onion
      - zcasha3cmfrpy7b7.onion
      - zcashz7ed3nvbdxm.onion
      - zcash5adwfpxfuvf.onion
      - zcashixg5ol2ndo4.onion
      - zcashuzwa365oh3n.onion
      - zcashskbeoiwtym3.onion
      - zcashuyvk5e7qfzy.onion
      - fhsxfrwpyrtoxeal.onion
      - zcash2iihed2wdux.onion
      - w3dxku36wbp3lowx.onion
      - zcashuhmzycmlwld.onion
  dogecoin:
    services: 0
    magic_number: c0.0.0.*
    port: 22556
    protocol_version: 70015
    min_protocol_version: 70003
    dns_seeds:
      - seed.multidoge.org
      - seed2.multidoge.org
      - doge.netcodepool.org
      - doge.cryptoculture.net
      - dogepool.pw
    address_seeds:
      - 95.85.29.*
      - 162.243.113.*
      - 146.185.181.*
      - 188.165.19.*
      - 166.78.155.*
      - 78.46.57.*
      - 147.135.101.*
      - 185.26.28.*
      - 161.97.165.*
      - 173.255.237.*
      - 51.91.66.*
      - 62.194.173.*
      - 139.162.205.*
      - 107.15.95.*
      - 76.103.7.*:22556
      - 3svlvcmm3xejer4n.onion:22556


exclude_ipv4_networks:
  - 0.0.0.*/8
  - 127.0.0.*
  - 100.64.0.*
  - 169.254.0.*
  - 192.0.0.*
  - 192.0.2.*
  - 192.88.99.*
  - 198.51.100.*
  - 198.18.0.*
  - 224.0.0.*
  - 233.252.0.*
  - 203.0.113.*
  - 240.0.0.*
  - 192.0.0.*
  - 192.0.0.*
  - 192.0.0.*
  - 192.0.0.*
  - 192.175.48.*
  - 192.31.196.*
  - 192.52.193.*
  - 255.255.255.*

priv_ipv4_networks:
  - 10.0.0.*
  - 172.16.0.*
  - 192.168.0.*

# Set to 1 to receive all txs (unused)
relay: 0

# List of excluded ASNs
exclude_asns: []

# List of excluded IPv6 networks
exclude_ipv6_networks: []

# Bogons are addresses outside the range of valid ipv4 addresses
exclude_ipv4_bogons: True

# Use median percentile +/- N interquartile ranges in place of block height to determine activity
inactive_use_iqr: False


